### ISSUE TITLE
upload file status return 200,but not in server

### ISSUE THREAD

**Issue by hxdyj** [hash-bang/express-middleware-upload#1]
html code:
` <form action="http://localhost:3000/up" method="POST" enctype="multipart/form-data">
      <input type="file" name="sf">
      <input type='submit' value='Upload!' />
    </form>
`

express code:
`app.use('/up', emu({
    path: path.join(__dirname, '/public')
}))
`

**Comment by hash-bang** [comment]
By default EMU looks for a multipart mime field by the name of `file`.

It seems from the above HTML code you are using `sf`.

Either change the field in your HTML or set `{field: 'sf'}` in the EMU backend options.

**Comment by hxdyj** [comment]
Thanks for your help.
Hope your project  has some full code example for different config.
